// прототип_temp/src/components/kpi-card.tsx
import { LucideIcon, TrendingUp, TrendingDown } from "lucide-react";
import { Card } from "./ui/card";

interface KPICardProps {
  title: string;
  value: string;
  icon: LucideIcon;
  trend?: "up" | "down" | "neutral";
  trendValue?: string;
}

export function KPICard({ title, value, icon: Icon, trend = "neutral", trendValue }: KPICardProps) {
  return (
    <Card className="p-4">
      <div className="flex items-center justify-between">
        <div className="space-y-2">
          <p className="text-sm text-muted-foreground">{title}</p>
          <p className="text-2xl font-semibold text-foreground">{value}</p>
          {trendValue && (
            <div className="flex items-center gap-1 text-xs">
              {trend === "up" && <TrendingUp className="h-3 w-3 text-green-600" />}
              {trend === "down" && <TrendingDown className="h-3 w-3 text-red-600" />}
              <span className={
                trend === "up" ? "text-green-600" : 
                trend === "down" ? "text-red-600" : 
                "text-muted-foreground"
              }>
                {trendValue}
              </span>
            </div>
          )}
        </div>
        <div className="p-2 bg-primary/10 rounded-lg">
          <Icon className="h-5 w-5 text-primary" />
        </div>
      </div>
    </Card>
  );
}

// web/src/app/shared/components/kpi-card/kpi-card.component.ts
import { Component, input } from '@angular/core';
import { KPIData } from '../../../core/models/analytics.model';
import { UiCardComponent } from '@streakflow/ui/card';

/**
 * KPICard - displays key performance indicator
 * This is a DUMB component - presentation only
 */
@Component({
  selector: 'app-kpi-card',
  standalone: true,
  imports: [UiCardComponent],
  templateUrl: './kpi-card.component.html',
  styleUrl: './kpi-card.component.scss'
})
export class KpiCardComponent {
  // Inputs
  readonly data = input.required<KPIData>();
}


<ui-card class="p-4">
  <div class="flex items-center justify-between">
    <div class="space-y-2">
      <!-- Title -->
      <p class="text-sm text-muted-foreground">{{ data().title }}</p>
      
      <!-- Value -->
      <p class="text-2xl font-semibold text-foreground">{{ data().value }}</p>
      
      <!-- Trend -->
      @if (data().trendValue) {
        <div class="flex items-center gap-1 text-xs">
          @if (data().trend === 'up') {
            <span class="text-green-600">↗️</span>
          } @else if (data().trend === 'down') {
            <span class="text-red-600">↘️</span>
          }
          <span [class]="
            data().trend === 'up' ? 'text-green-600' : 
            data().trend === 'down' ? 'text-red-600' : 
            'text-muted-foreground'
          ">
            {{ data().trendValue }}
          </span>
        </div>
      }
    </div>
    
    <!-- Icon -->
    @if (data().icon) {
      <div class="p-2 bg-primary/10 rounded-lg">
        <span class="text-2xl">{{ data().icon }}</span>
      </div>
    }
  </div>
</ui-card>
