// web/src/app/shared/components/habit-card/habit-card.component.ts
import { Component, input, output, computed, signal } from '@angular/core';
import { Habit } from '../../../core/models/habit.model';
import { HabitUtils } from '../../../core/utils/habit.utils';
import { UiButtonComponent } from '@streakflow/ui/button';
import { UiProgressComponent } from '@streakflow/ui/progress';
import { UiCardComponent } from '@streakflow/ui/card';

/**
 * Habit action state - discriminated union for all possible states
 */
type HabitActionState =
  | { kind: 'completed' }
  | { kind: 'multi'; current: number; target: number }
  | { kind: 'single' };

type ActionHandler = () => void;

/**
 * Pure function to resolve action based on state
 * No side effects - deterministic and testable
 */
function resolveAction(
  state: HabitActionState,
  registry: Record<HabitActionState['kind'], ActionHandler>
): ActionHandler {
  return registry[state.kind];
}

/**
 * HabitCard - displays habit information and controls
 * This is a DUMB component - presentation only
 */
@Component({
  selector: 'app-habit-card',
  standalone: true,
  imports: [
    UiButtonComponent, 
    UiProgressComponent, 
    UiCardComponent
  ],
  templateUrl: './habit-card.component.html',
  styleUrl: './habit-card.component.scss'
})
export class HabitCardComponent {
  // Inputs
  readonly habit = input.required<Habit>();

  // Outputs
  readonly markToday = output<void>();
  readonly incrementStep = output<void>();
  readonly undoToday = output<void>();

  // Local UI state (animation only)
  readonly isAnimating = signal(false);

  // Computed values for display
  readonly isMultiGoal = computed(() => HabitUtils.isMultiGoal(this.habit()));
  readonly isCompleted = computed(() => HabitUtils.isCompleted(this.habit()));
  readonly displayProgress = computed(() => 
    HabitUtils.calculateProgress(this.habit().currentStep, this.habit().goal)
  );
  readonly streakText = computed(() => HabitUtils.formatStreak(this.habit().currentStreak));
  readonly showUndoButton = computed(() => {
    const habit = this.habit();
    return habit.currentStep > 0 && !this.isCompleted();
  });

  // Computed state for action dispatch
  readonly actionState = computed((): HabitActionState => {
    const habit = this.habit();
    
    if (HabitUtils.isCompleted(habit)) {
      return { kind: 'completed' };
    }
    
    if (HabitUtils.isMultiGoal(habit)) {
      return { 
        kind: 'multi', 
        current: habit.currentStep, 
        target: habit.goal 
      };
    }
    
    return { kind: 'single' };
  });

  /**
   * Handles main action button click
   * Uses dispatch table pattern - no branching in handler
   */
  onActionClick(): void {
    const state = this.actionState();
    
    const actionByKind: Record<HabitActionState['kind'], ActionHandler> = {
      completed: () => this.emitUndo(),
      multi:     () => this.emitIncrement(),
      single:    () => this.emitMark(),
    };
    
    resolveAction(state, actionByKind)();
  }

  /**
   * Handles undo button click
   */
  onUndoClick(): void {
    this.emitUndo();
  }

  /**
   * Emits mark event with animation
   */
  private emitMark(): void {
    this.animate();
    this.markToday.emit();
  }

  /**
   * Emits increment event with animation
   */
  private emitIncrement(): void {
    this.animate();
    this.incrementStep.emit();
  }

  /**
   * Emits undo event with animation
   */
  private emitUndo(): void {
    this.animate();
    this.undoToday.emit();
  }

  /**
   * Triggers UI animation
   */
  private animate(): void {
    this.isAnimating.set(true);
    setTimeout(() => this.isAnimating.set(false), 300);
  }
}



<ui-card 
  [class]="'p-4 transition-all duration-300 ease-in-out hover:shadow-md group ' + 
    (isAnimating() ? 'scale-[0.98]' : 'hover:scale-[1.02]')"
>
  <div class="flex items-start justify-between mb-3">
    <div class="flex items-center gap-3">
      <!-- Habit Icon -->
      <span class="text-xl transition-transform duration-200">
        {{ habit().icon }}
      </span>
      
      <!-- Habit Info -->
      <div>
        <h3 class="font-medium text-foreground">{{ habit().name }}</h3>
        <div class="flex items-center gap-1 text-sm text-muted-foreground">
          <span class="text-orange-500">🔥</span>
          <span>{{ streakText() }}</span>
        </div>
      </div>
    </div>
    
    <!-- Action Buttons -->
    <div class="flex items-center gap-1">
      <!-- Undo button - show only when progress > 0 and not completed -->
      @if (showUndoButton()) {
        <ui-button
          variant="ghost"
          size="sm"
          (click)="onUndoClick()"
          class="h-8 w-8 p-0 opacity-0 group-hover:opacity-100 transition-opacity duration-200"
        >
          <span class="text-base">↩️</span>
        </ui-button>
      }
      
      <!-- Main action button -->
      <ui-button
        [variant]="isCompleted() ? 'secondary' : 'ghost'"
        size="sm"
        (click)="onActionClick()"
        [class]="'flex items-center gap-1 h-8 transition-all duration-300 ease-in-out ' +
          (isAnimating() ? 'scale-95' : 'hover:scale-105') + ' ' +
          (isCompleted() ? 'bg-[#DCFCE7] dark:bg-green-900/30 hover:bg-green-200 dark:hover:bg-green-900/50 text-green-800 dark:text-green-200' : '')"
      >
        <span [class]="'transition-transform duration-300 ease-in-out ' + 
          (isAnimating() ? 'scale-110' : '')">
          {{ isCompleted() ? '✓' : '○' }}
        </span>
        <span class="hidden sm:inline text-xs font-medium">
          {{ isCompleted() ? 'Done' : 'Mark' }}
        </span>
      </ui-button>
    </div>
  </div>
  
  <!-- Progress Section -->
  <div class="space-y-2">
    <!-- Label -->
    <div class="flex justify-between text-sm">
      <span class="text-muted-foreground">
        {{ isMultiGoal() ? 'Steps Today' : 'Today\'s Progress' }}
      </span>
      <span class="font-medium">
        {{ isMultiGoal() ? habit().currentStep + ' / ' + habit().goal : displayProgress() + '%' }}
      </span>
    </div>
    
    <!-- Progress Visualization -->
    @if (isMultiGoal()) {
      <!-- Multi-step progress -->
      <div class="flex gap-1">
        @for (step of [].constructor(habit().goal); track $index; let index = $index) {
          <div
            [class]="'h-1.5 flex-1 rounded-full transition-all duration-300 ease-in-out ' +
              (index < habit().currentStep
                ? 'bg-primary scale-105'
                : index === habit().currentStep && isAnimating()
                ? 'bg-primary/60 scale-105'
                : 'bg-muted')"
          />
        }
      </div>
    } @else {
      <!-- Single progress bar -->
      <ui-progress 
        [value]="displayProgress()" 
        class="h-2"
      />
    }
  </div>
</ui-card>

// prototype/src/components/habit-card.tsx
import { useState, useEffect } from "react";
import { CheckCircle, Circle, Flame, Undo2 } from "lucide-react";
import { Card } from "./ui/card";
import { Button } from "./ui/button";
import { Progress } from "./ui/progress";
import { toast } from "sonner@2.0.3";

interface HabitCardProps {
  id: string;
  name: string;
  emoji?: string;
  currentStreak: number;
  progress: number;
  goal?: number;
  isCompleted?: boolean;
  currentStep?: number;
  onMarkToday?: () => void;
  onIncrementStep?: () => void;
  onUndoToday?: () => void;
}

export function HabitCard({ 
  id,
  name, 
  emoji = "🎯", 
  currentStreak, 
  progress, 
  goal = 1,
  isCompleted = false,
  currentStep = 0,
  onMarkToday,
  onIncrementStep,
  onUndoToday
}: HabitCardProps) {
  const [isAnimating, setIsAnimating] = useState(false);
  const [justCompleted, setJustCompleted] = useState(false);

  // Unified logic based on goal
  const isMultiGoal = goal > 1;
  const currentProgress = currentStep || 0;
  const displayProgress = isMultiGoal ? (currentProgress / goal) * 100 : progress;
  const isFullyCompleted = isMultiGoal ? currentProgress >= goal : isCompleted;

  // Handle action button click
  const handleActionClick = () => {
    if (isFullyCompleted && onUndoToday) {
      // Undo action
      setIsAnimating(true);
      onUndoToday();
      toast.success("Habit unmarked for today", {
        duration: 2000,
      });
      setTimeout(() => setIsAnimating(false), 300);
    } else if (isMultiGoal && onIncrementStep) {
      // Increment step
      setIsAnimating(true);
      onIncrementStep();
      
      const newStep = currentProgress + 1;
      if (newStep >= goal) {
        setJustCompleted(true);
        setTimeout(() => setJustCompleted(false), 2000);
        toast.success(`🎉 Great job! ${name} completed!`, {
          duration: 3000,
        });
      } else {
        toast.success(`Progress: ${newStep}/${goal}`, {
          duration: 2000,
        });
      }
      
      setTimeout(() => setIsAnimating(false), 300);
    } else if (onMarkToday) {
      // Simple mark action
      setIsAnimating(true);
      setJustCompleted(true);
      onMarkToday();
      setTimeout(() => setJustCompleted(false), 2000);
      toast.success(`🎉 Great job! ${name} completed!`, {
        duration: 3000,
      });
      setTimeout(() => setIsAnimating(false), 300);
    }
  };

  // Render progress indicators for multi-goal habits
  const renderMultiGoalProgress = () => {
    if (!isMultiGoal) return null;

    return (
      <div className="flex gap-1 mt-2">
        {Array.from({ length: goal }).map((_, index) => (
          <div
            key={index}
            className={`h-1.5 flex-1 rounded-full transition-all duration-300 ease-in-out ${
              index < currentProgress
                ? "bg-primary scale-105"
                : index === currentProgress && isAnimating
                ? "bg-primary/60 scale-105"
                : "bg-muted"
            }`}
          />
        ))}
      </div>
    );
  };

  // Get button content based on state
  const getButtonContent = () => {
    if (isFullyCompleted) {
      return {
        icon: <CheckCircle className="h-4 w-4 text-green-600" />,
        text: "Done",
        variant: "secondary" as const,
        showUndo: currentProgress > 0
      };
    } else {
      return {
        icon: <Circle className="h-4 w-4" />,
        text: "Mark",
        variant: "ghost" as const,
        showUndo: currentProgress > 0 && currentProgress < goal
      };
    }
  };

  const buttonContent = getButtonContent();

  return (
    <Card className={`p-4 transition-all duration-300 ease-in-out border-border group hover:shadow-md ${
      justCompleted ? "ring-2 ring-green-500/20 bg-green-50/50 dark:bg-green-950/20" : "hover:shadow-md"
    } ${isAnimating ? "scale-[0.98]" : "hover:scale-[1.02]"}`}>
      <div className="flex items-start justify-between mb-3">
        <div className="flex items-center gap-3">
          <span className={`text-xl transition-transform duration-200 ${
            justCompleted ? "animate-bounce" : ""
          }`}>
            {emoji}
          </span>
          <div>
            <h3 className="font-medium text-foreground">{name}</h3>
            <div className="flex items-center gap-1 text-sm text-muted-foreground">
              <Flame className="h-3 w-3 text-orange-500" />
              <span>{currentStreak} day streak</span>
            </div>
          </div>
        </div>
        
        <div className="flex items-center gap-1">
          {/* Undo button - show only when progress is between 1 and Goal-1 */}
          {buttonContent.showUndo && (
            <Button
              variant="ghost"
              size="sm"
              onClick={onUndoToday}
              className="h-8 w-8 p-0 opacity-0 group-hover:opacity-100 transition-opacity duration-200"
              title="Undo"
            >
              <Undo2 className="h-3 w-3" />
            </Button>
          )}
          
          {/* Main action button */}
          <Button
            variant={buttonContent.variant}
            size="sm"
            onClick={handleActionClick}
            className={`flex items-center gap-1 h-8 transition-all duration-300 ease-in-out ${
              isAnimating ? "scale-95" : "hover:scale-105"
            } ${isFullyCompleted ? "bg-[#DCFCE7] dark:bg-green-900/30 hover:bg-green-200 dark:hover:bg-green-900/50 text-green-800 dark:text-green-200" : ""}`}
          >
            <span className={`transition-transform duration-300 ease-in-out ${
              isAnimating ? "scale-110" : ""
            }`}>
              {buttonContent.icon}
            </span>
            <span className="hidden sm:inline text-xs font-medium">
              {buttonContent.text}
            </span>
          </Button>
        </div>
      </div>
      
      <div className="space-y-2">
        {/* Steps Today label and counter for multi-goal habits */}
        {isMultiGoal && (
          <div className="flex justify-between text-sm">
            <span className="text-muted-foreground">Steps Today</span>
            <span className="font-medium">{currentProgress} / {goal}</span>
          </div>
        )}
        
        {/* Progress label for single-goal habits */}
        {!isMultiGoal && (
          <div className="flex justify-between text-sm">
            <span className="text-muted-foreground">Today's Progress</span>
            <span className="font-medium">{Math.round(displayProgress)}%</span>
          </div>
        )}
        
        {/* Progress visualization */}
        {isMultiGoal ? (
          renderMultiGoalProgress()
        ) : (
          <Progress 
            value={displayProgress} 
            className={`h-2 transition-all duration-300 ease-in-out ${
              justCompleted ? "bg-green-100 dark:bg-green-900/30" : ""
            }`}
          />
        )}
      </div>
    </Card>
  );
}
